### ISSUE TITLE
aarch64 not working with X11 (MACHINE_FEATURES += "vc4graphics")

### ISSUE THREAD

**Issue by Romaxx** [cosmo0920/rpi3-yocto-rocko#7]
Xorg server return (EE) no screens found(EE)

**Comment by cosmo0920** [comment]
> Then, run source ${YOCTO_ROOT_DIR}/oe-init-build-env and bitbake core-image-weston.

This line says that this configuration aims for Wayland/Weston.
I only confirmed core-image-weston in this repository.

I won't support X11.
